openapi: 3.0.1
info:
  title: Booking Service API
  version: "1.0"
paths:
  /bookings:
    post:
      summary: Create booking
      description: Create a new booking (checks device and user existence)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
      responses:
        "201":
          description: Booking created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        "400":
          description: Bad request (device/user not found)
          content:
            text/plain:
              schema: { type: string }
        "500":
          description: Internal error
          content:
            text/plain:
              schema: { type: string }
components:
  schemas:
    CreateBookingRequest:
      type: object
      required: [device_id, user_id, owner_id, start_date, end_date]
      properties:
        device_id: { type: string, example: dev-123 }
        user_id: { type: string, example: user-456 }
        owner_id: { type: string, example: owner-789 }
        start_date: { type: string, format: date-time }
        end_date: { type: string, format: date-time }
    Booking:
      type: object
      properties:
        id: { type: string }
        device_id: { type: string }
        user_id: { type: string }
        owner_id: { type: string }
        start_date: { type: string, format: date-time }
        end_date: { type: string, format: date-time }
        status: { type: string }
        created_at: { type: string, format: date-time }
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
