openapi: 3.0.0
info:
  title: Booking Service API
  description: API documentation for the Booking Service
  version: 1.0.0
servers:
  - url: http://localhost:8082

paths:
  /bookings:
    get:
      summary: Get All Bookings
      description: Retrieve a list of all bookings
      responses:
        '200':
          description: List of all bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'

    post:
      summary: Create Booking
      description: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
      responses:
        '201':
          description: Booking successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

  /bookings/{bookingID}:
    get:
      summary: Get Booking by ID
      parameters:
        - in: path
          name: bookingID
          required: true
          schema:
            type: string
          description: UUID of the booking
      responses:
        '200':
          description: Booking details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '400':
          description: Invalid booking ID
        '404':
          description: Booking not found

  /bookings/user/{userID}:
    get:
      summary: Get Bookings by User
      parameters:
        - in: path
          name: userID
          required: true
          schema:
            type: string
          description: UUID of the user
      responses:
        '200':
          description: List of user's bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '400':
          description: Invalid user ID

components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: string
        listing_id:
          type: string
        user_id:
          type: string
        owner_id:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateBookingRequest:
      type: object
      properties:
        listing_id:
          type: string
        user_id:
          type: string
        owner_id:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
      required:
        - listing_id
        - user_id
        - owner_id
        - start_time
        - end_time

  securitySchemes: # вот здесь должно быть
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
